# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Course'),
            preserve_default=False,
        ),
    ]
