# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Grupos',
                'verbose_name': 'Grupo',
            },
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='Platform',
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Plataforma', 'verbose_name_plural': 'Plataformas'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='course',
            new_name='platform',
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Platform'),
        ),
    ]
